services:
  vsftpd1:
    image: fauria/vsftpd
    container_name: vsftpd1
    ports:
      - "2100:21"
      - "30000-30009:30000-30009"
    environment:
      FTP_USER: user1
      FTP_PASS: pass1
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 30000
      PASV_MAX_PORT: 30009
    volumes:
      - ./vsftpd1:/home/vsftpd

  vsftpd2:
    image: fauria/vsftpd
    container_name: vsftpd2
    ports:
      - "2200:21"
      - "31000-31009:31000-31009"
    environment:
      FTP_USER: user2
      FTP_PASS: pass2
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 31000
      PASV_MAX_PORT: 31009
    volumes:
      - ./vsftpd2:/home/vsftpd
